### ISSUE TITLE
SpringBoot 3.1.11 Compatibility Issue

### ISSUE THREAD

**Issue by mahmoodfathy** [joutvhu/spring-dynamic-jpa#27]
I was trying to upgrade from java springboot 3.1.6 to 3.1.11 , but seems there is a Compatibility Issue in the later versions,
I have tested till springboot 3.1.8 works fine , but starting from 3.1.9 I get an error for no such method,probably due to a change in spring-data-jpa :

here is the stacktrace :
```java
Caused by: java.lang.NoSuchMethodError: 'org.springframework.data.jpa.repository.query.DeclaredQuery org.springframework.data.jpa.repository.query.ExpressionBasedStringQuery.deriveCountQuery(java.lang.String, java.lang.String)'
	at org.springframework.data.jpa.repository.query.DynamicBasedStringQuery.deriveCountQuery(DynamicBasedStringQuery.java:11)
	at com.joutvhu.dynamic.jpa.query.DynamicJpaRepositoryQuery.doCreateCountQuery(DynamicJpaRepositoryQuery.java:128)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.createCountQuery(AbstractJpaQuery.java:265)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.count(JpaQueryExecution.java:210)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.lambda$doExecute$0(JpaQueryExecution.java:205)
	at org.springframework.data.support.PageableExecutionUtils.getPage(PageableExecutionUtils.java:63)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.doExecute(JpaQueryExecution.java:204)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:92)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:149)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:137)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:244)
	at jdk.proxy2/jdk.proxy2.$Proxy312.findPagedByFilterRequest(Unknown Source)
```

Versions used:
java 17 
pom.xml
```
       <dependency>
            <groupId>com.github.joutvhu</groupId>
            <artifactId>spring-dynamic-jpa</artifactId>
            <version>3.0.8</version>
        </dependency>

        <dependency>
            <groupId>com.github.joutvhu</groupId>
            <artifactId>spring-dynamic-freemarker</artifactId>
            <version>1.0.1</version>
        </dependency>
```

**Comment by mahmoodfathy** [comment]
the issue is with this line https://github.com/joutvhu/spring-dynamic-jpa/blob/dab4b8953407e2043fd13a1320d355a7b18cd7e7/src/main/java/com/joutvhu/dynamic/jpa/query/DynamicJpaRepositoryQuery.java#L128.
JPA no longer has the signature deriveCountQuery(java.lang.String, java.lang.String) , it only has deriveCountQuery(java.lang.String)

**Comment by joutvhu** [comment]
Fixed in version `3.1.8`

**Comment by mahmoodfathy** [comment]
hey @joutvhu  you mean the version `3.1.8` of your library that is fixed in , or you mean the springboot version 3.1.8 couldn't quite get it

**Comment by mahmoodfathy** [comment]
@joutvhu  if you mean that i need to update your library to version 3.1.8 then it doesn't exist on maven , if you mean springboot v 3.1.8 then this what am reporting , am not sure why you closed the issue , am reporting that it is working till version 3.1.8 in springboot after that it fails , and I need to upgrade to latest 3.1.x version of springboot , if no further development will be done to your library then can you please let me know so I will refactor and remove your dependency ?

**Comment by joutvhu** [comment]
It's already on https://repo1.maven.org/maven2/com/github/joutvhu/spring-dynamic-jpa/3.1.8

It will take a few days for it to sync to https://mvnrepository.com as well as other repositories

**Comment by mahmoodfathy** [comment]
@joutvhu thanks for the clarifications and appreciate your work 🙏  , will try it out and let you know, appreciate your response
